---
Router1:
  hostname: 192.168.175.11
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Routers
Router2:
  hostname: 192.168.175.12
  port: 22
  username: cisco 
  password: cisco
  secret: cisco
  groups:
    - IOS_Routers
Router3:
  hostname: 192.168.175.13
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Routers
Switcher2:
  hostname: 192.168.175.15
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Switches
Switcher3:
  hostname: 192.168.175.16
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Switches
Router4:
  hostname: 192.168.175.18
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Routers
Router5:
  hostname: 192.168.175.19
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Routers
Switcher1:
  hostname: 192.168.175.14
  port: 22
  username: cisco
  password: cisco
  secret: cisco
  groups:
    - IOS_Switches
